site_name: Sucata
site_url: https://sucata.dev
theme:
  name: material
  language: en
  logo: images/icon.png
  favicon: images/icon.png
  palette:
    scheme: slate
    primary: blue grey
    scheme: slate
    accent: light blue
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.indexes

plugins:
  - search

repo_url: https://github.com/gumpdev/sucata
repo_name: gumpdev/sucata

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Concepts: getting-started/concepts.md
      - First Project:
          - Overview: getting-started/first-project/overview.md
          - Configuring the Project: getting-started/first-project/configuring-project.md
          - Creating a Player: getting-started/first-project/creating-player.md
  - Examples: examples.md
  - CLI: cli.md
  - References:
    - sucata.audio: references/sucata.audio.md
    - sucata.camera: references/sucata.camera.md
    - sucata.events: references/sucata.events.md
    - sucata.filesystem: references/sucata.filesystem.md
    - sucata.gamepad: references/sucata.gamepad.md
    - sucata.graphic: references/sucata.graphic.md
    - sucata.input: references/sucata.input.md
    - sucata.math: references/sucata.math.md
    - sucata.scene: references/sucata.scene.md
    - sucata.time: references/sucata.time.md
    - sucata.window: references/sucata.window.md
  - About: 
    - About: about/about.md
    - Third Party: about/third-party.md
